# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultanome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(567, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtNome = QtWidgets.QTextEdit(self.widget)
        self.txtNome.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtNome.setObjectName("txtNome")
        self.horizontalLayout.addWidget(self.txtNome)
        self.botaoBuscar = QtWidgets.QPushButton(self.widget)
        self.botaoBuscar.setObjectName("botaoBuscar")
        self.horizontalLayout.addWidget(self.botaoBuscar)
        self.verticalLayout.addWidget(self.widget)
        self.areaTxt = QtWidgets.QTextEdit(Form)
        self.areaTxt.setObjectName("areaTxt")
        self.verticalLayout.addWidget(self.areaTxt)
        self.label_filtros = QtWidgets.QLabel(Form)
        self.label_filtros.setObjectName("label_filtros")
        self.verticalLayout.addWidget(self.label_filtros)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Escreva seu nome para buscá-lo nos dados filtrados. </span><span style=\" font-size:10pt; color:#aa0000;\">Atenção: </span><span style=\" font-size:10pt; font-weight:600; color:#aa0000;\">Não utilize acentos!</span></p></body></html>"))
        self.txtNome.setPlaceholderText(_translate("Form", "Nome"))
        self.botaoBuscar.setText(_translate("Form", "Buscar"))
        self.label_filtros.setText(_translate("Form", "TextLabel"))
